storage: # type of config -> storage
  append : False # True (default if omitted) or False, if True append following to the partitions found with psutil.get_partitions
  root_dir:
    mountpoint: "/"
  gpfs0: # custom name for the mountpoint 
    mountpoint: "/gpfs0" # mountpoint (if doesn't exist ?)
    fstype : "gpfs" # filesystem type: checks fstype, if fstype does NOT match storage is assumed to be unmounted (optional)
  nfsshare:
    mountpoint: "/mynfs"
    fstype : "nfs"
  does_not_exist: # example that will generate error
    mountpoint: "/error" # might use for important partition you might need to monitor
    # fstype not checked since if it not specified
network:
  append : False #True # if True (default if omitted), show other interfaces after these, otherwise ignore others
  localhost:
    ifname: "lo*" # match start of the interface's name
  internet:
    ifname: "en0"
connection:
  # checks connection to following (host, port) pairs
  google-dns:
    host: "8.8.8.8"
    port: 53

